services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Y9uYMwWFZFeWbADB
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883 # MQTT (unencrypted)
      - 9001:9001 # WebSockets
      - 8883:8883 # MQTTS (TLS)
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./docker/mosquitto-pwfile:/mosquitto/config/pwfile:rw
      - ./docker/certs:/mosquitto/config/certs:ro # Mount certificates

  backend:
    build:
      context: ./projet_back
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./projet_back:/usr/src/app
      - /usr/src/app/node_modules # Évite d'écraser node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: sh -c "npm ci && npx nodemon --legacy-watch --config nodemon.json"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./projet_web_front
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./projet_web_front:/usr/src/app
    ports:
      - "8080:5173"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm ci && npm run dev -- --host"
