services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - ALLOW_ANONYMOUS=0
      - MQTT_USER=mosquitto
      - MQTT_PASSWORD=mosquitto

  backend:
    build:
      context: ./projet_back
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./projet_back:/usr/src/app
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    command: sh -c "npm ci && npm run dev"
    depends_on:
      - db
      - mqtt
